### ISSUE TITLE
MVP #2 New account creation, login, and guest/demo login

### ISSUE THREAD

**Issue by jeffdam** [jeffdam/crux#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by ronilbhatia** [comment]
![Screen Shot 2019-05-02 at 9 34 20 AM](https://user-images.githubusercontent.com/32026924/57091216-822b3800-6cbd-11e9-8af5-18f155cf98ec.png)
![Screen Shot 2019-05-02 at 9 34 43 AM](https://user-images.githubusercontent.com/32026924/57091234-8c4d3680-6cbd-11e9-8c75-9946bae3c768.png)

1. Add some padding to the left and right side of the navbars at the top, so that it is more in line with the styling on MountainProject's site. Right now your elements are pushed all the way to the edge.
2. Increase the font weight on the top navbar with all of the links to REI.

![Screen Shot 2019-05-02 at 9 42 20 AM](https://user-images.githubusercontent.com/32026924/57091717-ac312a00-6cbe-11e9-834c-30e874d84422.png)
![Screen Shot 2019-05-02 at 9 42 32 AM](https://user-images.githubusercontent.com/32026924/57091718-acc9c080-6cbe-11e9-90ce-e332b53dba9e.png)

3. All of the elements in the modal are too tall and not wide enough compared to the styling of MountainProject. Font sizes also seem a little too big on most elements, and the placeholder text should be a lighter gray with less font weight.
4. An 'X' in the upper-right of the modal like they have would be nice.
5. I think it would look better if you styled the 'Demo' button similar to the Log In button, instead of making it a small link at the bottom. We want to make it really easy for recruiters to demo login. I also think it shouldn't just fill in the input fields, but actually dispatch the action to login the demo user, so that user's don't have to then actually click the login button themselves.

Overall good job! The styling is pretty on point, the functionality is there, and I was able to navigate bug-free. Just fix the few styling things I mentioned above and we can close this out.

**Comment by jeffdam** [comment]
I corrected everything you mentioned. For the font, it took me a while to realize that I have to specifically import the weight of the font I chose. It should look correctly weighted now.

I'm not sure I did the demo login correctly. I worry that I just got lucky with the timing of the asynchronous stuff.

**Comment by ronilbhatia** [comment]
Really great job. You're site is looking really good, and I'm satisfied with all of the changes you made. I can stalk your code and see how you're handling the async demo login stuff but seems to be working so I am closing this out!
